# Generated by Django 5.2.6 on 2025-11-04 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_task_user_task_goals_task_user_id_ff5381_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['status', 'deadline', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='goals_task_user_id_ff5381_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['goal', 'is_done', 'due_date'], name='goals_task_goal_id_cd29ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_goal_title_per_user'),
        ),
    ]
